[build]
  base = "."   # This points to the root of your project if the frontend is in the root
  publish = "build"   # This points to the build directory after the React app is built
  command = "npm run build"  # Command to build your React app

[build.environment]
  NODE_VERSION = "20.17.0"  # Node.js version for Netlify to use


